name: .NET CI/CD with Jira Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish/

    # Jira Integration - Send build status to Jira
    - name: Notify Jira - Build Success
      if: success()
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ github.event.head_commit.message }}
        transition: "Done"
      env:
        JIRA_BASE_URL: https://andresvaldes1001.atlassian.net
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Notify Jira - Build Failed
      if: failure()
      uses: atlassian/gajira-comment@v3
      with:
        issue: ${{ github.event.head_commit.message }}
        comment: "❌ Build failed in GitHub Actions. Check the logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        JIRA_BASE_URL: https://andresvaldes1001.atlassian.net
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Code Analysis
      run: dotnet build --verbosity normal --configuration Release /p:TreatWarningsAsErrors=true
